const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

/**
 * Finds the nearest directory containing a .git folder, starting from the current working directory.
 * @returns {string|null} The path to the Git root or null if not found.
 */
function findGitRoot(startDir = process.cwd()) {
    let current = path.resolve(startDir);
    while (current !== path.parse(current).root) {
        if (fs.existsSync(path.join(current, '.git'))) {
            return current;
        }
        current = path.dirname(current);
    }
    return null;
}

// Configuration
const GIT_ROOT = findGitRoot();
const GLOBAL_LOG_ROOT = path.resolve(__dirname, '../../'); // ~/.gemini/skills/

// Determine the active log root: prefer project-local session_logs/ if in a Git repo.
const LOG_ROOT = GIT_ROOT || GLOBAL_LOG_ROOT;
const LOG_DIR = path.join(LOG_ROOT, 'session_logs');
const LOG_FILE = path.join(LOG_DIR, 'session-history.md');
const LATEST_FILE = path.join(LOG_DIR, 'latest-session.md');

function getTimestamp() {
    const now = new Date();
    const iso = now.toISOString();
    return iso.split('.')[0].slice(0, 16).replace('T', ' ');
}

function getDailyAggregation(logFilePath, dateStr) {
    if (!fs.existsSync(logFilePath)) return null;
    const content = fs.readFileSync(logFilePath, 'utf8');
    
    // Split by newline followed by ## to avoid splitting on ###
    const sections = content.split('\n## ');
    
    // The first section might have the main header, but it won't start with [
    const todayEntriesRaw = sections.filter(s => s.trim().startsWith(`[${dateStr}]`));
    
    if (todayEntriesRaw.length === 0) return null;

    let combinedSummary = "";
    let combinedTasks = "";

    // Oldest to newest (todayEntriesRaw is newest to oldest)
    const chronologicalEntries = [...todayEntriesRaw].reverse();

    chronologicalEntries.forEach((entry, index) => {
        const titleLine = entry.split('\n')[0];
        const title = titleLine.replace(/\[.*?\] /, '').trim();
        
        const summaryPart = entry.split('### Summary')[1];
        const tasksPart = entry.split('### Pending Tasks')[1];
        
        if (summaryPart && tasksPart) {
            const summaryText = summaryPart.split('### Pending Tasks')[0].trim();
            const tasksText = tasksPart.split('---')[0].trim();
            
            combinedSummary += `### ${title}\n${summaryText}\n\n`;
            combinedTasks += `#### From ${title}\n${tasksText}\n\n`;
        }
    });

    return {
        summary: combinedSummary.trim(),
        tasks: combinedTasks.trim()
    };
}

function logSession(title, summary, tasks) {
    const timestamp = getTimestamp();
    const dateStr = new Date().toLocaleDateString();
    
    const historyEntry = `
## [${dateStr}] ${title}
**Timestamp:** \`${timestamp}\`

### Summary
${summary}

### Pending Tasks
${tasks}

---
`;

    try {
        if (!fs.existsSync(LOG_DIR)) {
            fs.mkdirSync(LOG_DIR, { recursive: true });
        }

        const header = '# Gemini Session History\n\n';
        if (!fs.existsSync(LOG_FILE)) {
            fs.writeFileSync(LOG_FILE, header + historyEntry);
        } else {
            const currentContent = fs.readFileSync(LOG_FILE, 'utf8');
            const contentWithoutHeader = currentContent.startsWith(header) 
                ? currentContent.slice(header.length) 
                : currentContent;
            
            const updatedContent = header + historyEntry + contentWithoutHeader;
            fs.writeFileSync(LOG_FILE, updatedContent);
        }

        const aggregation = getDailyAggregation(LOG_FILE, dateStr);
        const latestSummary = aggregation && aggregation.summary ? aggregation.summary : summary;
        const latestTasks = aggregation && aggregation.tasks ? aggregation.tasks : tasks;

        const latestContent = `---
type: daily-session-capture
date: ${dateStr}
last_update: ${timestamp}
---
# Daily Activity Summary: ${dateStr}

## Detailed Activity Log
${latestSummary}

## Consolidated Pending Tasks
${latestTasks}

---
*Generated by Gemini CLI - Session Logger*
`;

        fs.writeFileSync(LATEST_FILE, latestContent);

        // If in a Git repository, stage and commit the changes
        if (GIT_ROOT) {
            process.chdir(GIT_ROOT);
            execSync(`git add "${path.relative(GIT_ROOT, LOG_FILE)}" "${path.relative(GIT_ROOT, LATEST_FILE)}"`);
            execSync(`git commit -m "docs: session log - ${title}"`);
        }

        console.log(`Success: Logged "${title}" in ${LOG_ROOT} and updated daily summary.`);
    } catch (error) {
        console.error(`Error logging session: ${error.message}`);
        process.exit(1);
    }
}

const args = process.argv.slice(2);
if (args.length < 3) {
    console.log('Usage: node log_session.cjs "<title>" "<summary>" "<tasks>"');
    process.exit(1);
}

logSession(args[0], args[1], args[2]);
